spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: sbahadirersoz
    password: password
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service